[
    {id:'0', type:'output', data:{label:'dhaba-chicken'}, position:{x:'0', y:'0'}},
    {id:'1', type:'input', data:{label:'chicken'}, position:{x:'0', y:'0'}},
    {id:'1-1', type:'output', data:{label:'diced-chicken'}, position:{x:'0', y:'0'}},
    {id:'2', type:'input', data:{label:'ginger'}, position:{x:'0', y:'0'}},
    {id:'2-1', type:'output', data:{label:'diced-ginger'}, position:{x:'20', y:'20'}},
    {id:'3', type:'input', data:{label:'garlick'}, position:{x:'0', y:'0'}},
    {id:'3-1', type:'output', data:{label:'crushed-garlic'}, position:{x:'0', y:'0'}},
    {id:'4', type:'input', data:{label:'onion'}, position:{x:'0', y:'0'}},
    {id:'4-1', type:'output', data:{label:'diced-onion'}, position:{x:'0', y:'0'}},
    {id:'5', type:'input', data:{label:'green-pepper'}, position:{x:'0', y:'0'}},
    {id:'5-1', type:'output', data:{label:'chopped-green-pepper'}, position:{x:'0', y:'0'}},
    {id:'6', type:'input', data:{label:'black-pepper'}, position:{x:'0', y:'0'}},
    {id:'6-1', type:'output', data:{label:'crushed-black-pepper'}, position:{x:'0', y:'0'}},
    {id: '7', type:'input', data:{label:'magic-two'}, position:{x:'0', y:'0'}},
    {id: 'cut-1-1-1', source: '1', target: '1-1', label: 'cut a bit', labelStyle:{fill: 'red', fontWeight: 700}},
    {id: 'dice-2-2-1', source: '2', target: '2-1' },
    {id: 'crush-3-3-1', source: '3', target: '3-1' },
    {id: 'dice-4-4-1', source: '4', target: '4-1', label: 'dice-onions', labelStyle:{fill: 'blue', fontWeight: 900}},
    {id: 'dice-5-5-1', source: '5', target: '5-1' },
    {id: 'crush-6-6-1', source: '6', target: '6-1' },
    {id: 'mix-1', source: '7', target: '0' },
    {id: 'mix-2', source: '2', target: '0' }
    ];
